### ISSUE TITLE
Unable get timeline and mention

### ISSUE THREAD

**Issue by chenshaoju** [twip/twip#72]
Sorry for my English.

在24小时前，我使用Twidere+Twip时遇到一个问题，刷新Timeline没有反应，包括 timeline ,mention 和DM。

通过curl去获取 home_timeline.json ，返回了如下错误：

```
curl HOST/t/o/CODE/1.1/statuses/home_timeline.json
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```

通过开启Twip的log和debug，能看到Twitter API返回了内容，但是客户端收不到。

如果通过curl去获得一个错误的地址，比如 curl HOST/t/o/CODE/1.1/statuses/abcdefg ，则能返回一个Twitter的错误页面。

在 @mariotaku 的帮助下，发现所有json array的都挂了，为了排除服务器的问题，于是我新开了一个VPS，搭建了一个全新的Apache 2.4.25 +PHP  7.0.19-1 ，没启用HTTPS，再次执行获取 home_timeline.json 的curl，结果有不同的错误：

```
 Problem (2) in the Chunked-Encoded data
```

我不知道该如何继续了，有没有什么方法可以进一步的诊断并解决该问题？

谢谢。

**Comment by mariotaku** [comment]
不知是否和 cURL 版本相关： https://stackoverflow.com/questions/29146515/curl-problem-2-in-the-chunked-encoded-data

Is this issue related to cURL?

**Comment by chenshaoju** [comment]
我用Chrome的开发人员工具分析了一下，请求数据后服务器没有发回任何数据就断开连接了，客户端发出的RST，可能是因为“空”的原因，cURL出现这个提示。

但是我还没搞清楚是怎么回事。。。

**Comment by tenwx** [comment]
发现同样的问题，开了twip debug后看到twitter api返回结果是正常的，但通过twip返回就会response empty

**Comment by chenshaoju** [comment]
该问题在今天重试后，发现已经恢复了。

初步怀疑是PHP 7的某个旧版本有问题，导致了该现象。

目前使用的PHP版本暂时没有问题：
```
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
```

此issue暂时关闭，有问题再Open。
